# Publish all joint states -----------------------------------
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

gazebo_ros_control:
  pid_gains:
    LF_WHEEL_JOINT:
      p: 100.0
    RF_WHEEL_JOINT:
      p: 100.0
    LH_WHEEL_JOINT:
      p: 100.0
    RH_WHEEL_JOINT:
      p: 100.0

 # Base frame_id
  base_frame_id: base_link

  # Odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.
  enable_odom_tf: false

  # Smb hardware provides wheel velocities
  estimate_velocity_from_position: false

  # Wheel separation and radius multipliers

  wheel_separation_multiplier: 3.0 # default: 1.0
  wheel_radius_multiplier    : 0.7 # default: 1.0
  # wheel_separation_multiplier: 1.875 # default: 1.0
  # wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 2.0   # m/s
      # max_velocity           : 1.1   # m/s
      has_acceleration_limits: true
      max_acceleration       : 5.0   # m/s^2
      # max_acceleration       : 2.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 2.0   # rad/s
      # max_velocity           : 1.1   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 5.0   # rad/s^2
      # max_acceleration       : 3.0   # rad/s^2

smb_diff_drive:
  type: "diff_drive_controller/DiffDriveController"
  # left_wheel: ['LF_WHEEL_JOINT']
  # right_wheel: ['RF_WHEEL_JOINT']
  left_wheel: ['LF_WHEEL_JOINT', 'LH_WHEEL_JOINT']
  right_wheel: ['RF_WHEEL_JOINT', 'RH_WHEEL_JOINT']
  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  # pose_covariance_diagonal: [0.1, 0.001, 0.001, 0.001, 0.001, 0.3]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  cmd_vel_timeout: 0.25
  velocity_rolling_window_size: 2